version: '3'

services:

  webapp:
    build: .
    command: python /app/covid19/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - .:/app

  database:
    image: postgres:11-alpine
    container_name: database
    environment:
      POSTGRES_PASSWORD: mybestpwdCovid19
      POSTGRES_USER: jairo
      POSTGRES_DB: covid
    ports:
      - 5432:5432