version: '3'

services:

  webapp:
    build: .
    container_name: webapp
    command: python /app/myproyect/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      DB_URL: 'postgresql://jairo:mybestpwd@database:5432/production'
      DEBUG: 'False'
      SECRET_KEY: 'IXCJ123XC@S!EAAVFYW549GER4GXC?!DAXZ@FSQR'

  database:
    image: postgres:11-alpine
    container_name: database
    environment:
      POSTGRES_PASSWORD: mybestpwd
      POSTGRES_USER: jairo
      POSTGRES_DB: production
    ports:
      - 5432:5432
    volumes:
      - /opt/pgdata:/var/lib/postgresql/data